-- 3. List the first and last name of all authors, separated by a space, (name the column 'author') and the average star rating of their books (name the column 'average_rating').
-- Order by the average rating, lowest first. Where there is a tie in average rating, use a secondary order of author (full name), ascending.
-- (16 rows)
